#!/usr/bin/env python3
"""gen_tools_index.py — generiše docs/TOOLS.md iz docstring-ova alata.

Grupisanje ide po prefiksu imena fajla (psf_/qnx6_/basic_/pre_writer_/
orion_/run_/...). Prva linija docstringa je opis. Pokretanje:

    python3 scripts/gen_tools_index.py
"""
from __future__ import annotations

import ast
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

GROUPS: list[tuple[str, str, tuple[str, ...]]] = [
    ("Firmware extraction", "Read-only readers for the QNX images that hold the navigation parsers.",
     ("qnx6_extract", "fw_protection_model")),
    ("MIB PSF60 source decoding", "Reading the newer MIB map files (`PSF2DDTM`, version `60DREID4ADAS7`).",
     ("psf_decode", "basic_", "pre_writer_layers", "mib_graph_spatial_extract", "audiurban_")),
    ("Original 3G Plus reference profiling", "Read-only profilers of the original Orion `.ATLAS` databases used as the writer reference.",
     ("orion_psd_reference_profile", "orion_schema_", "orion_property_", "orion_item_", "orion_vidtable_",
      "orion_xac_", "orion_edge_", "orion_centerline_geometry_decode", "orion_graph_spatial_probe",
      "orion_mib_", "orion_layer_survey", "orion_block_header_profile", "orion_block_key_spatial_probe",
      "orion_nonkey_block_profile", "orion_uncovered_block_probe", "orion_index_block_profile",
      "orion_tile_grid_probe", "orion_lzma_failure_probe")),
    ("Orion column codec and object writers", "Column codec primitives and the decoded-chunk writers that produce Orion objects from MIB source rows.",
     ("orion_column_codec", "orion_object_writer", "orion_centerline_writer", "orion_merged_graph_writer",
      "orion_clothoid")),
    ("ATLAS container: decode, verify, write", "HEADER / REVISION / INDEX / CONTAINER grammar, the spatial block key, block round-trip and the full-file assembler.",
     ("orion_atlas_header_decode", "orion_container_header_decode", "orion_block_grammar_verify",
      "orion_index_decode", "orion_index_root_decode", "orion_block_writer", "orion_tile_formula_verify",
      "orion_cell_partition", "orion_cell_chunk_writer", "orion_cells_geojson", "orion_atlas_assemble",
      "orion_conf_write")),
    ("Repeatable Ghidra evidence runners", "Headless Ghidra batches that regenerate the firmware evidence quoted in the docs.",
     ("run_basic_geometry_re", "run_basic_handle2_re", "run_basic_road_attributes_re", "run_basic_urban_semantics_re",
      "run_pre_writer_layers_re", "run_orion_column_codec_re", "run_psd15_profile_re", "run_ghidra_sharded_grep")),
    ("Stage runners and orchestration", "Full-corpus stages with cross-checks, plus the JSON-manifest pipeline runners.",
     ("run_", "orion_stage_watcher")),
]


def first_doc_line(path: Path) -> str:
    try:
        doc = ast.get_docstring(ast.parse(path.read_text(encoding="utf-8"))) or ""
    except SyntaxError:
        return "(syntax error)"
    line = (doc.strip().splitlines() or ["(no docstring)"])[0].strip()
    prefix = f"{path.name} — "
    if line.startswith(prefix):
        line = line[len(prefix):]
    return line


def group_of(name: str) -> int:
    for i, (_, _, prefixes) in enumerate(GROUPS):
        for p in prefixes:
            if name.startswith(p) and not (p == "run_" and any(name.startswith(x) for x in GROUPS[5][2])):
                return i
    return len(GROUPS)


def main() -> None:
    tools = sorted((REPO / "tools").glob("*.py"))
    legacy = sorted((REPO / "legacy" / "mmi3g-atlas").glob("*.py"))
    buckets: dict[int, list[Path]] = {}
    for t in tools:
        buckets.setdefault(group_of(t.stem), []).append(t)

    lines = [
        "# Tool index",
        "",
        "Generated by `scripts/gen_tools_index.py` from the first docstring line of",
        f"every script. {len(tools)} tools in `tools/`, {len(legacy)} in `legacy/mmi3g-atlas/`.",
        "All are Python 3 standard library only; every tool prints `--help`.",
        "Docstrings are in English or Serbian depending on when the tool was written.",
        "",
    ]
    for i, (title, blurb, _) in enumerate(GROUPS):
        items = buckets.get(i, [])
        if not items:
            continue
        lines += [f"## {title}", "", blurb, "", "| Tool | Purpose |", "|---|---|"]
        lines += [f"| `tools/{t.name}` | {first_doc_line(t)} |" for t in items]
        lines.append("")
    rest = buckets.get(len(GROUPS), [])
    if rest:
        lines += ["## Other", "", "| Tool | Purpose |", "|---|---|"]
        lines += [f"| `tools/{t.name}` | {first_doc_line(t)} |" for t in rest]
        lines.append("")
    lines += ["## Legacy MMI 3G Plus research tools", "",
              "The original Orion/ATLAS reverse-engineering scripts (August 2026). Kept as they were;",
              "their story is in `legacy/mmi3g-atlas/DOCS.md`.", "",
              "| Tool | Purpose |", "|---|---|"]
    lines += [f"| `legacy/mmi3g-atlas/{t.name}` | {first_doc_line(t)} |" for t in legacy]
    lines += ["", "## Pipeline manifests", "",
              "| File | Purpose |", "|---|---|",
              "| `tools/orion_container_pipeline.json` | 9-stage container verification pipeline (header, grammar, index, root, block round-trip, spatial key, formula, grid, assembler round-trip) for `run_container_pipeline.py`. |",
              "| `tools/orion_xac_pipeline.json` | XAC vector/name bridge stages for `orion_stage_watcher.py`. |",
              "", "## Ghidra scripts", "",
              "`ghidra_scripts/*.java` are generic headless helpers (function listing, decompile, xrefs, pointer tables, string xrefs)",
              "used by the `run_*_re.py` runners. `legacy/mmi3g-atlas/ghidra_scripts/*.java` are the earlier NavCore probes.", ""]
    out = REPO / "docs" / "TOOLS.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO)}: {len(tools)} tools, {len(legacy)} legacy")


if __name__ == "__main__":
    main()
